//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TeeMsEntities : DbContext
{
    public TeeMsEntities()
        : base("name=TeeMsEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<assignment> assignment { get; set; }
    public DbSet<assignment_component> assignment_component { get; set; }
    public DbSet<assignment_person> assignment_person { get; set; }
    public DbSet<group> group { get; set; }
    public DbSet<group_member> group_member { get; set; }
    public DbSet<group_role> group_role { get; set; }
    public DbSet<login> login { get; set; }
    public DbSet<organization> organization { get; set; }
    public DbSet<person> person { get; set; }
    public DbSet<project> project { get; set; }
    public DbSet<role> role { get; set; }
    public DbSet<project_group> project_group { get; set; }
    public DbSet<assignment_component_person> assignment_component_person { get; set; }
    public DbSet<project_person> project_person { get; set; }
    public DbSet<comment> comment { get; set; }
}
